### ISSUE TITLE
Can't compile Gateway-MQTT project

### ISSUE THREAD

**Issue by Lama1121** [feanor-anglin/GetWired-Project#14]
I'm getting following error when compiling Gateway-MQTT
_Arduino: 1.8.13 (Windows 10), Board: "ATmega328, No bootloader, EEPROM retained, 328PB, BOD 2.7V, LTO disabled, External 8 MHz"_

_c:/rob/arduino-1.8.13/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: C:\Users\WJCWSM~1.EUR\AppData\Local\Temp\arduino_build_885427/Gateway-MQTT.ino.elf section `.data' will not fit in region `text'_

_c:/rob/arduino-1.8.13/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: region `text' overflowed by 70 bytes_

_collect2.exe: error: ld returned 1 exit status_

_exit status 1_

_Error compiling for board ATmega328._
Using UIPEthernet version 2.0.9
and MySensors version 2.3.2

**Comment by feanor-anglin** [comment]
Please enable LTO, it should help.
