### ISSUE TITLE
Missing SHTSensor.h

### ISSUE THREAD

**Issue by kolczak** [feanor-anglin/GetWired-Project#18]
`GetWired New Firmware/main.ino` file contains 
```
#include "SHTSensor.h"
```
I can't find this file anywhere. Should that include be removed?

**Comment by feanor-anglin** [comment]
All libraries needed to compile are [here](https://github.com/feanor-anglin?tab=repositories). The library for SHT sensor should also be there, but of course you can remove this include if you are not willing to use any SHT sensors.
